server:
  port: 8090

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS : false

  data.mongodb:
    database: user_db
    port: 27017
    host: localhost

logging:
   pattern.console: '[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n'
   file:
      path: '/Users/makt/logs/'


